language: go

go:
  - 1.2
  - 1.3
  - tip

install:
  - go get golang.org/x/tools/cmd/cover
  - go get -d -v ./... && go build -v ./...

script:
  - go test -v -covermode=count -coverprofile=coverage.out

after_script:
  - go get github.com/mattn/goveralls
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

matrix:
  allow_failures:
    - go: tip

env:
  global:
    secure: Ts22TMsMIUxy2eTYF1pee7RNjYmFkwC9m+VaBDQroRtrabeGyQDHdTkjLzYgYJ+8zx3Tf75Tx5y0CzjDPKzQjLN1k+i89NAg2iEZ9b2G3WQslYpXaXtDiERSYYsRQMMx3Or/GoE172io8m6Kp9yszDgzfQdtGVz6mwUcSOQJPhM=
